import { defineField, defineType } from "sanity";

export const briefRequestSchema = defineType({
  name: "briefRequest",
  title: "Brief Request",
  type: "document",
  groups: [
    { name: "crm", title: "CRM", default: true },
    { name: "submitted", title: "Submitted (read-only)" },
    { name: "meta", title: "Meta" },
  ],
  fields: [
    // ─── CRM (editable by the team) ────────────────────────────────
    defineField({
      name: "status",
      title: "Status",
      type: "string",
      group: "crm",
      options: {
        list: [
          { title: "New", value: "new" },
          { title: "Reviewing", value: "reviewing" },
          { title: "Contacted", value: "contacted" },
          { title: "Won", value: "won" },
          { title: "Lost", value: "lost" },
          { title: "Archived", value: "archived" },
        ],
        layout: "radio",
      },
      initialValue: "new",
    }),
    defineField({
      name: "priority",
      title: "Priority",
      type: "string",
      group: "crm",
      options: {
        list: [
          { title: "Low", value: "low" },
          { title: "Medium", value: "medium" },
          { title: "High", value: "high" },
          { title: "Urgent", value: "urgent" },
        ],
        layout: "radio",
      },
      initialValue: "medium",
    }),
    defineField({
      name: "leadScore",
      title: "Lead score (1-5)",
      type: "number",
      group: "crm",
      validation: (r) => r.min(1).max(5).integer(),
    }),
    defineField({
      name: "assignedTo",
      title: "Assigned to",
      type: "string",
      group: "crm",
      description: "Who's handling this lead.",
    }),
    defineField({
      name: "nextAction",
      title: "Next action",
      type: "string",
      group: "crm",
      description: "What needs to happen next (short line).",
    }),
    defineField({
      name: "nextActionDate",
      title: "Next action date",
      type: "date",
      group: "crm",
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      group: "crm",
      of: [{ type: "string" }],
      options: { layout: "tags" },
    }),
    defineField({
      name: "internalNotes",
      title: "Internal notes",
      type: "array",
      group: "crm",
      of: [{ type: "block" }],
      description: "Private notes visible only to the team.",
    }),

    // ─── Submitted content (read-only snapshot of what was sent) ────
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "submitted",
      readOnly: true,
      validation: (r) => r.required(),
    }),
    defineField({
      name: "contactName",
      title: "Contact name",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "contactEmail",
      title: "Contact email",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "company",
      title: "Company",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "companySize",
      title: "Company size (employees)",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "companyAge",
      title: "Company age",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "companyRevenue",
      title: "Annual revenue (BRL)",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "estimatedRange",
      title: "Estimated range (BRL)",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "workFor",
      title: "Work for",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "brand",
      title: "Brand",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "requestType",
      title: "Request type",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "requestSubtype",
      title: "Request subtype",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "creativeLevel",
      title: "Creative level",
      type: "string",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "deadline",
      title: "Deadline",
      type: "date",
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "description",
      title: "Description",
      type: "text",
      rows: 6,
      group: "submitted",
      readOnly: true,
    }),
    defineField({
      name: "files",
      title: "Uploaded files",
      type: "array",
      group: "submitted",
      readOnly: true,
      of: [{ type: "file" }],
    }),
    defineField({
      name: "references",
      title: "References / inspiration",
      type: "array",
      group: "submitted",
      readOnly: true,
      of: [{ type: "file" }],
    }),
    defineField({
      name: "referenceLinks",
      title: "Reference links",
      type: "array",
      group: "submitted",
      readOnly: true,
      of: [{ type: "string" }],
    }),
    defineField({
      name: "payload",
      title: "Raw payload",
      description: "Full form answers as submitted.",
      type: "text",
      rows: 10,
      group: "submitted",
      readOnly: true,
    }),

    // ─── Meta (system fields) ───────────────────────────────────────
    defineField({
      name: "source",
      title: "Source",
      type: "string",
      group: "meta",
      readOnly: true,
    }),
    defineField({
      name: "submittedAt",
      title: "Submitted at",
      type: "datetime",
      group: "meta",
      readOnly: true,
    }),
  ],
  preview: {
    select: {
      title: "title",
      company: "company",
      status: "status",
      type: "requestType",
    },
    prepare: ({ title, company, status, type }) => ({
      title: title || "Untitled brief",
      subtitle: [company, type, status].filter(Boolean).join(" · "),
    }),
  },
  orderings: [
    {
      title: "Newest",
      name: "submittedAtDesc",
      by: [{ field: "submittedAt", direction: "desc" }],
    },
  ],
});
